// ENUMS
export type Provider = 'GOOGLE' | 'DISCORD' | 'GITHUB';
export type Role = 'USER' | 'ADMIN';
export type ProgressStatus = 'AHEAD' | 'ON_TRACK' | 'BEHIND' | 'VERY_BEHIND' | 'COMPLETED';
export type Difficulty = 'VERY_EASY' | 'EASY' | 'MEDIUM' | 'HARD' | 'VERY_HARD';
// Priority stopped being a fixed union ('LOW'|'MEDIUM'|'HIGH') the moment
// it became an admin-managed catalog (see AdminPriority/PriorityOption
// below) - it's just whatever key the admin's Priority rows use, a plain
// string, same as `type`/`academicType` already were.
export type SecurityEventType = 'RATE_LIMIT_EXCEEDED';
// No longer fixed union types: now they come from the DB (a table the
// admin can edit), so they're `string` (the "key" returned by /tasks/meta).
export type TaskType = string;
export type AcademicTaskType = string;

// Shape returned by /tasks/meta to populate selects
export interface TaskTypeOption {
  key: string;
  label: string;
  colorHex?: string | null;
}

export interface AcademicTaskTypeOption {
  key: string;
  label: string;
  taskTypeKey: string; // which TaskType it belongs to, e.g. "ACADEMIC"
}

export interface TaskMeta {
  taskTypes: TaskTypeOption[];
  academicTaskTypes: AcademicTaskTypeOption[];
  difficulties: string[];
  priorities: PriorityOption[];
  progressStatuses: string[];
}

// POST /tasks/import request row - see backend's ImportTaskRowDto. Built
// on the frontend by mapping the spreadsheet's Area/Type NAME columns to
// the IDs/keys the backend expects (see utils/parseTaskImportFile.ts).
export interface ImportTaskRow {
  areaId: string;
  periodId?: string;
  title: string;
  date: string;
  type: string;
  academicType?: string;
  topics?: string;
  weightPercentage?: number;
  difficulty?: Difficulty;
  progressStatus?: ProgressStatus;
  targetGrade?: number;
  realGrade?: number;
}

// POST /tasks/import response.
export interface ImportTaskRowResult {
  row: number;
  success: boolean;
  taskId?: string;
  error?: string;
}

export interface ImportTasksResult {
  created: number;
  failed: number;
  results: ImportTaskRowResult[];
}

// Uma aula concreta, já gravada (GET /schedule). Ver comentário completo
// no model ClassOccurrence do schema.prisma para o "porquê" de não haver
// recorrência/exceções aqui - isto é sempre uma ocorrência real e datada.
export interface ClassOccurrence {
  id: string;
  userId: string;
  date: string;
  startMinutes: number;
  endMinutes: number;
  subject: string;
  location: string | null;
  professor: string | null;
  externalUid: string;
}

// Uma linha já parseada de um .ics (ver utils/parseIcsSchedule.ts) - é o
// que vai no body de POST /schedule/import.
export interface ImportScheduleRow {
  date: string;
  startMinutes: number;
  endMinutes: number;
  subject: string;
  location?: string;
  professor?: string;
  externalUid: string;
}

export interface ImportScheduleRowResult {
  row: number;
  success: boolean;
  error?: string;
}

export interface ImportScheduleResult {
  imported: number;
  failed: number;
  results: ImportScheduleRowResult[];
}

// GET /study-plan response.
export interface StudyPlanSuggestion {
  date: string;
  startMinutes: number;
  endMinutes: number;
  taskId: string;
  taskTitle: string;
}

export interface StudyPlanResult {
  suggestions: StudyPlanSuggestion[];
  warnings: string[];
}

// Full records used only by the admin area (/admin/task-types,
// /admin/academic-task-types) - distinct from the *Option types above
// (those are the "trimmed down" version for populating selects, coming
// from /tasks/meta). Note: there's no editable "key" here on purpose -
// it's auto-generated by the backend from the label and never exposed for
// editing (only the label, color, order, and active/inactive state are).
export interface AdminTaskType {
  id: string;
  key: string;
  label: string;
  colorHex: string | null;
  order: number;
  isActive: boolean;
  academicTaskTypes: { id: string; key: string; label: string; isActive: boolean }[];
}

export interface AdminAcademicTaskType {
  id: string;
  key: string;
  label: string;
  order: number;
  isActive: boolean;
  taskTypeId: string;
  taskType: { id: string; key: string; label: string; colorHex: string | null } | null;
}

export interface AdminPriority {
  id: string;
  key: string;
  label: string;
  colorHex: string | null;
  order: number;
  isActive: boolean;
}

// Shape returned in TaskMeta.priorities (see /tasks/meta) - same trimmed
// "for populating selects" shape as TaskTypeOption, now that Priority is
// a real admin-managed catalog instead of a fixed enum.
export interface PriorityOption {
  key: string;
  label: string;
  colorHex: string | null;
}

// 
// MODELS
// 

// Bate certo com o enum CommuteMode do schema.prisma e com os valores
// aceites pela Google Distance Matrix API (em minúsculas no pedido - ver
// ScheduleService.estimateCommute).
export type CommuteMode = 'DRIVING' | 'WALKING' | 'BICYCLING' | 'TRANSIT';

export type UserStatus = 'ACTIVE' | 'SUSPENDED' | 'BANNED';

export interface User {
  id: string;
  email: string;
  role: Role;
  name: string | null;
  avatarUrl: string | null;
  createdAt: string;
  // true if the account already has a password credential (via Supabase
  // Auth) - false for accounts that only ever signed in via OAuth. Never
  // exposes supabaseAuthId itself, only this boolean.
  hasPassword: boolean;

  // Só vem preenchido nas respostas de admin (GET/PATCH /users, /users/:id)
  // - ver USER_ADMIN_SELECT em users.service.ts. Opcional aqui porque
  // /auth/me (o "eu" da app, ver AuthContext) não os devolve.
  status?: UserStatus;
  suspendedUntil?: string | null;
  statusReason?: string | null;
  statusUpdatedAt?: string | null;
  statusUpdatedBy?: { id: string; name: string | null; email: string } | null;

  // Active dashboard (selected Program + Period) - null while
  // AcademicContext hasn't resolved/created the default "General" yet.
  activeProgramId: string | null;
  activePeriodId: string | null;

  // Horário/plano de estudo (Fase 6) - todos opcionais, null = nunca
  // configurado. Ver CommuteSettingsCard.tsx e Schedule.tsx.
  commuteMinutes: number | null;
  // Nem todo o estudante tem carro - ver comentário completo em
  // CommuteMode no schema.prisma. Sempre definido (tem @default no
  // schema), nunca null.
  commuteMode: CommuteMode;
  homeAddress: string | null;
  campusAddress: string | null;
  quietHoursStart: number | null;
  quietHoursEnd: number | null;

  // Optional relations (depends on what your backend returns)
  areas?: Area[];
  tasks?: Task[];
}

export type AppealResolution = 'APPROVED' | 'DENIED';

export interface AppealSummary {
  id: string;
  createdAt: string;
  resolution: AppealResolution | null;
  resolutionNote: string | null;
  resolvedAt: string | null;
}

// GET /account-status/me - alimenta o AccountBlockedPage.
export interface AccountStatusInfo {
  status: UserStatus;
  suspendedUntil: string | null;
  statusReason: string | null;
  statusUpdatedAt: string | null;
  appeal: AppealSummary | null;
}

// Vista de admin (GET /appeals) - além de tudo o que AppealSummary já
// tem, inclui quem submeteu e quem resolveu.
export interface AppealAdmin extends AppealSummary {
  message: string;
  statusAtSubmission: UserStatus;
  reasonAtSubmission: string | null;
  user: { id: string; name: string | null; email: string };
  resolvedBy: { id: string; name: string | null; email: string } | null;
}


export interface AcademicProgram {
  id: string;
  userId: string;
  name: string;
  gradeScale: string;
  isActive: boolean;
  order: number;
  createdAt: string;
  // Default for whether each subject's final grade is rounded to the
  // nearest whole number before the credit-weighted average is computed.
  // Periods can override this individually (see AcademicPeriod.roundFinalGrade).
  roundFinalGrade: boolean;
}

export interface AcademicPeriod {
  id: string;
  programId: string;
  name: string;
  startDate: string;
  endDate: string | null;
  isArchived: boolean;
  archivedAt: string | null;
  // When true, this is the period its program auto-selects on switch/reload
  // instead of the chronologically most recent one - see togglePeriodPin.
  isPinned: boolean;
  createdAt: string;
  // Overrides AcademicProgram.roundFinalGrade for this period. null = inherit
  // the program's default.
  roundFinalGrade: boolean | null;
}

// Returned by GET /periods/:id/average and GET /programs/:id/average.
// average === null when there isn't any graded task yet (realGrade set) -
// distinct from 0, which would be a real (very bad) average.
export interface WeightedAverage {
  average: number | null;
  gradedTaskCount: number;
  // Sum of the weights (credits, at the program/period level) actually
  // used to compute `average` - used by the dashboard credit simulator to
  // project "what if I add one more graded item" client-side.
  totalWeight: number;
}

export interface PeriodAverage extends WeightedAverage {
  periodId: string;
  periodName: string;
}

export interface ProgramAverage extends WeightedAverage {
  programId: string;
  programName: string;
}

// Returned by GET /programs/:id/periods-comparison - one item per period
// of the program, ordered by startDate asc.
export interface PeriodComparisonEntry extends WeightedAverage {
  periodId: string;
  periodName: string;
  startDate: string;
  isArchived: boolean;
}

// Returned by GET /programs/:id/credits.
export interface CreditsAreaSummary {
  areaId: string;
  areaName: string;
  credits: number | null;
  average: number | null;
  passed: boolean;
}

export interface CreditsSummary {
  programId: string;
  programName: string;
  gradeScale: string;
  passThreshold: number;
  earnedCredits: number;
  attemptedCredits: number;
  areas: CreditsAreaSummary[];
}

export interface Area {
  id: string;
  userId: string;
  name: string;
  colorHex: string;
  // Key of the TaskType this Area defaults to (null = no type associated).
  defaultTaskType: string | null;
  // Credits (ECTS or equivalent) for this course. null = no credits set
  // (e.g. secondary school) - enters with weight 1 in the average calculation.
  credits: number | null;
  // Só vem preenchido quando GET /areas foi chamado com um periodId
  // concreto - nunca usado para esconder a Area, só para agrupar/ordenar
  // no seletor do Notebook (ver NotebookSubjectPicker).
  usedInPeriod?: boolean;
}

export interface Task {
  id: string;
  userId: string;
  areaId: string;
  title: string;
  date: string; // ISO String format from backend

  // Which period (semester/academic year) this task belongs to.
  periodId: string;
  
  // Typology
  type: TaskType;
  academicType: AcademicTaskType | null;
  topics: string | null;
  notes: string | null;
  isPinned: boolean;
  // Manual drag-and-drop order in TaskGrid - lower first. Set via
  // PATCH /tasks/reorder (reorderTasks in userService.ts).
  sortOrder: number;

  // Execution Metadata
  weightPercentage: number | null;
  difficulty: Difficulty;
  // Nullable, ao contrário de difficulty - ver comentário em priorityId no
  // schema.prisma (opcional de propósito). priorityLabel/priorityColorHex
  // vêm prontos do backend (toResponse) para as badges não precisarem de
  // cruzar com a lista de /tasks/meta só para mostrar um texto e uma cor.
  priority: string | null;
  priorityLabel: string | null;
  priorityColorHex: string | null;
  // Ordem de /admin/priorities (menor = mais prioritário), null sem
  // prioridade - só usado pelo modo de ordenação "Priority" em Tasks.tsx.
  priorityOrder: number | null;
  // Histórico, nunca decresce - ver comentário em schema.prisma. Conta
  // qualquer vez que a data mudou para mais tarde, não só o botão rápido
  // "+1 Day".
  postponedCount: number;
  progressStatus: ProgressStatus;
  referenceLink: string | null;
  // How long you expect this task to take, in minutes. Manual estimate -
  // see api/predictionService.ts for the model-generated suggestion.
  estimatedMinutes: number | null;
  
  // Evaluation
  targetGrade: number | null;
  realGrade: number | null;
  
  // Integrations & Timestamps
  googleCalendarEventId: string | null;
  // Duration (minutes) of the Google Calendar event, only relevant when
  // the task has a time set. Null = backend defaults to 60min.
  calendarDurationMinutes: number | null;
  createdAt: string;
  completedAt: string | null; // Actual moment it moved to COMPLETED
  lastOverdueCheckAt: string | null; // Last time the overdue check-in asked about this task

  // Optional relations
  area?: Area;
}

export interface ApiKey {
  id: string;
  userId: string;
  keyHash: string;
  name: string;
  createdAt: string;
  lastUsed: string | null;
}

// Only ADMIN if the key was explicitly created with that scope by an
// admin user - see backend AuthService.generateApiKey(), which refuses
// to honor a requested ADMIN scope from anyone whose own Role isn't
// already ADMIN.
export type ApiKeyScope = 'TASKS' | 'ADMIN';

// What GET /auth/api-keys actually returns - never includes keyHash or
// userId, just enough for the user to recognize and manage their keys.
export interface ApiKeySummary {
  id: string;
  name: string;
  scope: ApiKeyScope;
  createdAt: string;
  lastUsed: string | null;
}

export interface Identity {
  id: string;
  userId: string;
  provider: Provider;
  providerAccountId: string;
  accessToken: string | null;
  refreshToken: string | null;
  scope: string | null;
  createdAt: string;
}

export interface SecurityLog {
  id: string;
  type: SecurityEventType;
  ip: string;
  method: string;
  path: string;
  userAgent: string | null;
  createdAt: string;
  userId: string | null;
  user: { id: string; email: string; name: string | null } | null;
}

export interface PaginatedSecurityLogs {
  total: number;
  skip: number;
  take: number;
  logs: SecurityLog[];
}

export interface SecurityLogsStats {
  totalLastHour: number;
  totalLast24h: number;
  topOffenders: { ip: string; count: number }[];
}

export interface BannedIp {
  id: string;
  ip: string;
  reason: string | null;
  createdAt: string;
  bannedByUserId: string | null;
  bannedBy: { id: string; name: string | null; email: string } | null;
}

// FOCUS / STUDY SESSIONS

export interface StudySession {
  id: string;
  startedAt: string;
  endedAt: string | null;
  note: string | null;
  taskId: string | null;
  areaId: string | null;
  task: { id: string; title: string } | null;
  area: { id: string; name: string; colorHex: string } | null;
  // null while the session is active (endedAt doesn't exist yet)
  durationSeconds: number | null;
}

export interface HeatmapCell {
  dayOfWeek: number; // 0 (Sunday) - 6 (Saturday)
  hourBucket: number; // 0 (00h-04h) - 5 (20h-24h)
  totalMinutes: number;
  sessionCount: number;
}
export type AgentTriggerMode = 'ANY' | 'ALL';
export type AgentFailMode = 'CLOSED' | 'OPEN';

export interface AgentConfig {
  triggerMode: AgentTriggerMode;
  hasOverdueTasks: boolean;
  hasOverdueCheckins: boolean;
  minDifficultyToday: Difficulty | null;
  anyTaskToday: boolean;
  minProgressStatus: ProgressStatus | null;
  blockedProcesses: string[];
  blockedDomains: string[];
  failMode: AgentFailMode;
  pollIntervalSeconds: number;
  isConfigured: boolean;
}
// --- Notebook ---------------------------------------------------------

export interface StrokePoint {
  x: number;
  y: number;
  pressure?: number;
}

// Um traço vetorial completo - ver comentário em NotebookEntry.drawingStrokes
// no schema.prisma para o "porquê" de não guardar um PNG rasterizado.
export interface Stroke {
  points: StrokePoint[];
  color: string;
  width: number;
}

// Uma tabela estruturada dentro de uma entrada - ver comentário em
// NotebookEntry.tables no schema.prisma. `id` é só para servir de
// key/referência local ao editar; gerado no frontend, o backend guarda-o
// tal como vem.
export interface NotebookTable {
  id: string;
  rows: string[][];
}

// Uma etiqueta de texto solta no canvas (não presa a nenhuma forma) -
// para escrever palavras/frases com o teclado por cima do desenho à
// mão, em vez de só símbolos/formas. x/y são o canto superior esquerdo,
// nas mesmas coordenadas fixas do viewBox (ver VIEW_WIDTH/VIEW_HEIGHT em
// NotebookCanvas.tsx). fontSize/color são opcionais no que vem da API
// (entradas antigas não os têm) - o frontend aplica um default ao ler.
export interface CanvasTextItem {
  id: string;
  x: number;
  y: number;
  text: string;
  fontSize?: number;
  color?: string;
}

// Ícone posicionável no canvas - ver comentário em
// NotebookEntry.canvasShapes no schema.prisma. x/y/width/height nas
// mesmas coordenadas fixas do viewBox do canvas (ver VIEW_WIDTH/
// VIEW_HEIGHT em NotebookCanvas.tsx), não em pixels de ecrã.
export type CanvasShapeType = 'router' | 'switch' | 'firewall' | 'server' | 'pc' | 'cloud' | 'ap';

export interface CanvasShape {
  id: string;
  type: CanvasShapeType;
  x: number;
  y: number;
  width: number;
  height: number;
  label: string;
}

// Uma ligação entre duas formas - recalculada a cada render a partir da
// posição atual de fromShapeId/toShapeId (ver clipPointToRectEdge em
// canvasGeometry.ts), por isso "segue" a forma quando é arrastada, sem
// guardar coordenadas próprias. Se uma forma referenciada for apagada, a
// ligação fica órfã e deixa de ser desenhada (ver NotebookCanvas.tsx) -
// na prática nunca acontece porque apagar uma forma apaga também as suas
// ligações (removeLinksForShape).
export interface CanvasLink {
  id: string;
  fromShapeId: string;
  toShapeId: string;
  label: string;
}

export interface NotebookPhoto {
  id: string;
  notebookEntryId: string;
  storagePath: string;
  position: number;
  // Signed URL gerado pelo backend a cada leitura, expira sozinho - nunca
  // guardar isto entre navegações.
  url: string | null;
}

// Ficheiro geral anexado a uma entrada (PDF, DOCX/PPTX/XLSX, ZIP,
// código/texto) - ver comentário em NotebookAttachment no schema.prisma.
// originalFileName é o nome tal como foi enviado, para mostrar/descarregar;
// extension é o tipo real validado no backend (pode não bater certo com a
// extensão do originalFileName, se o utilizador tiver enviado um ficheiro
// mal nomeado).
export interface NotebookAttachment {
  id: string;
  notebookEntryId: string;
  storagePath: string;
  originalFileName: string;
  extension: string;
  sizeBytes: number;
  // Signed URL com download forçado, gerado pelo backend a cada leitura.
  url: string | null;
}

// Um link guardado à parte do textContent - ver comentário em
// NotebookEntry.usefulLinks no schema.prisma.
export interface UsefulLink {
  id: string;
  label: string;
  url: string;
}

export type NotebookEntryType = 'NOTE' | 'STUDY' | 'CLASS';

export interface NotebookEntry {
  id: string;
  userId: string;
  areaId: string;
  classOccurrenceId: string | null;
  title: string;
  entryType: NotebookEntryType;
  // Só tem significado quando entryType é 'CLASS' - ver comentário no
  // schema.prisma sobre porque não é derivado do título.
  classNumber: number | null;
  textContent: string | null;
  drawingStrokes: Stroke[] | null;
  tables: NotebookTable[] | null;
  canvasShapes: CanvasShape[] | null;
  canvasLinks: CanvasLink[] | null;
  canvasTexts: CanvasTextItem[] | null;
  usefulLinks: UsefulLink[] | null;
  // Altura do viewBox do whiteboard (largura fica sempre fixa em 800) -
  // null/undefined = usa o default (ver DEFAULT_CANVAS_HEIGHT em
  // NotebookCanvas.tsx). Extensível pelo botão "Add more space", em vez
  // de suportar várias boards por entrada (mais simples, resolve o mesmo
  // problema de "ficar sem espaço").
  canvasHeight: number | null;
  date: string;
  photos: NotebookPhoto[];
  attachments: NotebookAttachment[];
}

export interface NotebookSearchResult extends NotebookEntry {
  area: { id: string; name: string; colorHex: string };
}

// Forma pública devolvida por GET /notebook/shared/:token - de propósito
// mais pequena que NotebookEntry (sem id/userId/areaId/classOccurrenceId
// internos), ver NotebookService.getSharedEntry no backend.
export interface SharedNotebookEntry {
  title: string;
  entryType: NotebookEntryType;
  classNumber: number | null;
  textContent: string | null;
  drawingStrokes: Stroke[] | null;
  tables: NotebookTable[] | null;
  canvasShapes: CanvasShape[] | null;
  canvasLinks: CanvasLink[] | null;
  canvasTexts: CanvasTextItem[] | null;
  canvasHeight: number | null;
  usefulLinks: UsefulLink[] | null;
  date: string;
  area: { name: string; colorHex: string };
  photos: NotebookPhoto[];
  attachments: NotebookAttachment[];
}

export interface ScheduleLinkResult {
  scheduleSubject: string | null;
}

export interface DetectClassResult {
  occurrence: ClassOccurrence | null;
}
