// ENUMS
export type Provider = 'GOOGLE' | 'DISCORD' | 'GITHUB';
export type Role = 'USER' | 'ADMIN';
export type ProgressStatus = 'AHEAD' | 'ON_TRACK' | 'BEHIND' | 'VERY_BEHIND' | 'COMPLETED';
export type Difficulty = 'VERY_EASY' | 'EASY' | 'MEDIUM' | 'HARD' | 'VERY_HARD';
export type SecurityEventType = 'RATE_LIMIT_EXCEEDED';
// No longer fixed union types: now they come from the DB (a table the
// admin can edit), so they're `string` (the "key" returned by /tasks/meta).
export type TaskType = string;
export type AcademicTaskType = string;

// Shape returned by /tasks/meta to populate selects
export interface TaskTypeOption {
  key: string;
  label: string;
  colorHex?: string | null;
}

export interface AcademicTaskTypeOption {
  key: string;
  label: string;
  taskTypeKey: string; // which TaskType it belongs to, e.g. "ACADEMIC"
}

export interface TaskMeta {
  taskTypes: TaskTypeOption[];
  academicTaskTypes: AcademicTaskTypeOption[];
  difficulties: string[];
  progressStatuses: string[];
}

// POST /tasks/import request row - see backend's ImportTaskRowDto. Built
// on the frontend by mapping the spreadsheet's Area/Type NAME columns to
// the IDs/keys the backend expects (see utils/parseTaskImportFile.ts).
export interface ImportTaskRow {
  areaId: string;
  periodId?: string;
  title: string;
  date: string;
  type: string;
  academicType?: string;
  topics?: string;
  weightPercentage?: number;
  difficulty?: Difficulty;
  progressStatus?: ProgressStatus;
  targetGrade?: number;
  realGrade?: number;
}

// POST /tasks/import response.
export interface ImportTaskRowResult {
  row: number;
  success: boolean;
  taskId?: string;
  error?: string;
}

export interface ImportTasksResult {
  created: number;
  failed: number;
  results: ImportTaskRowResult[];
}

// Full records used only by the admin area (/admin/task-types,
// /admin/academic-task-types) - distinct from the *Option types above
// (those are the "trimmed down" version for populating selects, coming
// from /tasks/meta). Note: there's no editable "key" here on purpose -
// it's auto-generated by the backend from the label and never exposed for
// editing (only the label, color, order, and active/inactive state are).
export interface AdminTaskType {
  id: string;
  key: string;
  label: string;
  colorHex: string | null;
  order: number;
  isActive: boolean;
  academicTaskTypes: { id: string; key: string; label: string; isActive: boolean }[];
}

export interface AdminAcademicTaskType {
  id: string;
  key: string;
  label: string;
  order: number;
  isActive: boolean;
  taskTypeId: string;
  taskType: { id: string; key: string; label: string; colorHex: string | null } | null;
}

// 
// MODELS
// 

export interface User {
  id: string;
  email: string;
  role: Role;
  name: string | null;
  avatarUrl: string | null;
  createdAt: string;
  // true if the account already has a password credential (via Supabase
  // Auth) - false for accounts that only ever signed in via OAuth. Never
  // exposes supabaseAuthId itself, only this boolean.
  hasPassword: boolean;

  // Active dashboard (selected Program + Period) - null while
  // AcademicContext hasn't resolved/created the default "General" yet.
  activeProgramId: string | null;
  activePeriodId: string | null;

  // Optional relations (depends on what your backend returns)
  areas?: Area[];
  tasks?: Task[];
}

export interface AcademicProgram {
  id: string;
  userId: string;
  name: string;
  gradeScale: string;
  isActive: boolean;
  order: number;
  createdAt: string;
  // Default for whether each subject's final grade is rounded to the
  // nearest whole number before the credit-weighted average is computed.
  // Periods can override this individually (see AcademicPeriod.roundFinalGrade).
  roundFinalGrade: boolean;
}

export interface AcademicPeriod {
  id: string;
  programId: string;
  name: string;
  startDate: string;
  endDate: string | null;
  isArchived: boolean;
  archivedAt: string | null;
  // When true, this is the period its program auto-selects on switch/reload
  // instead of the chronologically most recent one - see togglePeriodPin.
  isPinned: boolean;
  createdAt: string;
  // Overrides AcademicProgram.roundFinalGrade for this period. null = inherit
  // the program's default.
  roundFinalGrade: boolean | null;
}

// Returned by GET /periods/:id/average and GET /programs/:id/average.
// average === null when there isn't any graded task yet (realGrade set) -
// distinct from 0, which would be a real (very bad) average.
export interface WeightedAverage {
  average: number | null;
  gradedTaskCount: number;
  // Sum of the weights (credits, at the program/period level) actually
  // used to compute `average` - used by the dashboard credit simulator to
  // project "what if I add one more graded item" client-side.
  totalWeight: number;
}

export interface PeriodAverage extends WeightedAverage {
  periodId: string;
  periodName: string;
}

export interface ProgramAverage extends WeightedAverage {
  programId: string;
  programName: string;
}

// Returned by GET /programs/:id/periods-comparison - one item per period
// of the program, ordered by startDate asc.
export interface PeriodComparisonEntry extends WeightedAverage {
  periodId: string;
  periodName: string;
  startDate: string;
  isArchived: boolean;
}

// Returned by GET /programs/:id/credits.
export interface CreditsAreaSummary {
  areaId: string;
  areaName: string;
  credits: number | null;
  average: number | null;
  passed: boolean;
}

export interface CreditsSummary {
  programId: string;
  programName: string;
  gradeScale: string;
  passThreshold: number;
  earnedCredits: number;
  attemptedCredits: number;
  areas: CreditsAreaSummary[];
}

export interface Area {
  id: string;
  userId: string;
  name: string;
  colorHex: string;
  // Key of the TaskType this Area defaults to (null = no type associated).
  defaultTaskType: string | null;
  // Credits (ECTS or equivalent) for this course. null = no credits set
  // (e.g. secondary school) - enters with weight 1 in the average calculation.
  credits: number | null;
}

export interface Task {
  id: string;
  userId: string;
  areaId: string;
  title: string;
  date: string; // ISO String format from backend

  // Which period (semester/academic year) this task belongs to.
  periodId: string;
  
  // Typology
  type: TaskType;
  academicType: AcademicTaskType | null;
  topics: string | null;
  notes: string | null;
  isPinned: boolean;

  // Execution Metadata
  weightPercentage: number | null;
  difficulty: Difficulty;
  progressStatus: ProgressStatus;
  referenceLink: string | null;
  // How long you expect this task to take, in minutes. Manual estimate -
  // see api/predictionService.ts for the model-generated suggestion.
  estimatedMinutes: number | null;
  
  // Evaluation
  targetGrade: number | null;
  realGrade: number | null;
  
  // Integrations & Timestamps
  googleCalendarEventId: string | null;
  // Duration (minutes) of the Google Calendar event, only relevant when
  // the task has a time set. Null = backend defaults to 60min.
  calendarDurationMinutes: number | null;
  createdAt: string;
  completedAt: string | null; // Actual moment it moved to COMPLETED
  lastOverdueCheckAt: string | null; // Last time the overdue check-in asked about this task

  // Optional relations
  area?: Area;
}

export interface ApiKey {
  id: string;
  userId: string;
  keyHash: string;
  name: string;
  createdAt: string;
  lastUsed: string | null;
}

// Only ADMIN if the key was explicitly created with that scope by an
// admin user - see backend AuthService.generateApiKey(), which refuses
// to honor a requested ADMIN scope from anyone whose own Role isn't
// already ADMIN.
export type ApiKeyScope = 'TASKS' | 'ADMIN';

// What GET /auth/api-keys actually returns - never includes keyHash or
// userId, just enough for the user to recognize and manage their keys.
export interface ApiKeySummary {
  id: string;
  name: string;
  scope: ApiKeyScope;
  createdAt: string;
  lastUsed: string | null;
}

export interface Identity {
  id: string;
  userId: string;
  provider: Provider;
  providerAccountId: string;
  accessToken: string | null;
  refreshToken: string | null;
  scope: string | null;
  createdAt: string;
}

export interface SecurityLog {
  id: string;
  type: SecurityEventType;
  ip: string;
  method: string;
  path: string;
  userAgent: string | null;
  createdAt: string;
  userId: string | null;
  user: { id: string; email: string; name: string | null } | null;
}

export interface PaginatedSecurityLogs {
  total: number;
  skip: number;
  take: number;
  logs: SecurityLog[];
}

export interface SecurityLogsStats {
  totalLastHour: number;
  totalLast24h: number;
  topOffenders: { ip: string; count: number }[];
}

// FOCUS / STUDY SESSIONS

export interface StudySession {
  id: string;
  startedAt: string;
  endedAt: string | null;
  note: string | null;
  taskId: string | null;
  areaId: string | null;
  task: { id: string; title: string } | null;
  area: { id: string; name: string; colorHex: string } | null;
  // null while the session is active (endedAt doesn't exist yet)
  durationSeconds: number | null;
}

export interface HeatmapCell {
  dayOfWeek: number; // 0 (Sunday) - 6 (Saturday)
  hourBucket: number; // 0 (00h-04h) - 5 (20h-24h)
  totalMinutes: number;
  sessionCount: number;
}
export type AgentTriggerMode = 'ANY' | 'ALL';
export type AgentFailMode = 'CLOSED' | 'OPEN';

export interface AgentConfig {
  triggerMode: AgentTriggerMode;
  hasOverdueTasks: boolean;
  hasOverdueCheckins: boolean;
  minDifficultyToday: Difficulty | null;
  anyTaskToday: boolean;
  minProgressStatus: ProgressStatus | null;
  blockedProcesses: string[];
  blockedDomains: string[];
  failMode: AgentFailMode;
  pollIntervalSeconds: number;
  isConfigured: boolean;
}